# Generated by Django 5.2.3 on 2026-05-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
                ('word_type', models.CharField(choices=[('Noun', 'Noun'), ('Verb', 'Verb'), ('Adjective', 'Adjective'), ('Adverb', 'Adverb'), ('Technical', 'Technical/Coding')], default='Noun', max_length=20)),
                ('meaning', models.TextField()),
                ('example_sentence', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
