# Generated by Django 6.0.7 on 2026-07-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorlog',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
