# Generated by Django 6.0.7 on 2026-08-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_analytics', '0002_visitorlog_city_visitorlog_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorlog',
            name='is_tor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='is_vpn_proxy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='isp',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='network_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
