# Generated by Django 6.0.6 on 2026-07-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
